version: "3.8" 
services:
  frontend:
    image: ghcr.io/tobiasbak/fortune-cookie/frontend:${VERSION_TAG}
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
      target: production
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=localhost
  frontend-debug:
    image: ghcr.io/tobiasbak/fortune-cookie/frontend:${VERSION_TAG}-debug
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
      target: debug
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=localhost

  backend:
    image: ghcr.io/tobiasbak/fortune-cookie/backend:${VERSION_TAG}
    build:
      context: ./backend
      dockerfile: ../Dockerfile
      target: production
    environment:
      - REDIS_DNS=redis
  backend-debug:
    image: ghcr.io/tobiasbak/fortune-cookie/backend:${VERSION_TAG}-debug
    build:
      context: ./backend
      dockerfile: ../Dockerfile
      target: debug
    environment:
      - REDIS_DNS=redis

      
