version: "3.8" 
services:
  frontend:
    image: fortune-cookie-frontend:${VERSION_TAG}
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=localhost

  backend:
    image: fortune-cookie-backend:${VERSION_TAG}
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    environment:
      - REDIS_DNS=redis
      
