version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=localhost

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    environment:
      - REDIS_DNS=redis
      
