version: "3.8" 
services:
  frontend:
    image: ghcr.io/tobiasbak/fortune-cookie/frontend:${VERSION_TAG}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - 8080:8080
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=backend
  frontend-debug:
    image: ghcr.io/tobiasbak/fortune-cookie/frontend:${VERSION_TAG}-debug
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: debug
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=localhost

  backend:
    image: ghcr.io/tobiasbak/fortune-cookie/backend:${VERSION_TAG}
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - 9000:9000
    environment:
      - REDIS_DNS=redis
  backend-debug:
    image: ghcr.io/tobiasbak/fortune-cookie/backend:${VERSION_TAG}-debug
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: debug
    ports:
      - 9001:9001
    environment:
      - REDIS_DNS=redis
