apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: fortune-cookie-frontend
        image: ghcr.io/tobiasbak/fortune-cookie/frontend:latest
        env:
          - name: BACKEND_HOST
            value: backend
          - name: BACKEND_PORT
            value: "9000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
