name: Deployment

# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  Deploymnent:
    runs-on: ubuntu-latest
    steps:
      - name: clone-repository
        uses: actions/checkout@v3

      - name: copy kubeconfig secret
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: deploying on cluster
        run: kubectl --kubeconfig kubeconfig apply -f kubernetes/.