name: Deployment

# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: clone-repository
        uses: actions/checkout@v3

      - name: copy kubeconfig secret
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: cat frontend yaml file
        run: cat kubernetes/frontend-deployment.yaml

      - name: deploying on cluster
        run: kubectl --kubeconfig kubeconfig apply -f kubernetes/.