name: Development

env:
  docker_username: ${{ github.repository_owner }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  VERSION_TAG: 0.0.1-dev

on: 
  push:
    branches-ignore: 
     - "main"

jobs:
  print:
    if: ${{ needs.pr-check.outputs.number }} == 'null' || needs.pr-check.outputs.number == 0
    runs-on: ubuntu-latest
    outputs:
      docker_username: ${{ steps.step1.outputs.docker_username }}
      VERSION_TAG: ${{ steps.step1.outputs.VERSION_TAG }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: step1
        run: |
          echo "docker_username: $docker_username"
          echo "docker_username=$docker_username" >> $GITHUB_OUTPUT
          echo "VERSION_TAG: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_OUTPUT
          echo ${{ needs.pr-check.outputs.number }}
  Testing:
    uses: ./.github/workflows/testing.yml
    if: needs.pr-check.outputs.number == null
    permissions:
      packages: write
    with:
      docker_username: ${{ needs.print.outputs.docker_username }}
      VERSION_TAG: ${{ needs.print.outputs.VERSION_TAG }}
    secrets:
      docker_password: ${{ secrets.GITHUB_TOKEN }}
