name: Main
on: push
jobs: 
  Build:
    runs-on: ubuntu-latest
    container: golang:bookworm
    steps:
      - name: clone-down
        uses: actions/checkout@v3
      - name: Test
        run: chmod +x ci/unit-test.sh && ci/unit-test.sh
