name: Main

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Testing:
    uses: ./.github/workflows/testing.yml
    permissions:
      packages: write
    with:
      docker_username: ${{ github.repository_owner }}
      VERSION_TAG: 0.0.1
    secrets:
      docker_password: ${{ secrets.GITHUB_TOKEN }}



  Deployment:
    needs:
      - Docker-functional-testing
      - Test
    uses: ./.github/workflows/deployment.yml
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
