name: Main
env:
  docker_username: ${{ github.repository_owner }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  VERSION_TAG: 0.0.1

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Testing:
    uses: ./.github/workflows/testing.yml
    permissions:
      packages: write

  Deployment:
    needs:
      - Docker-functional-testing
      - Test
    uses: ./.github/workflows/deployment.yml
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
