name: Main
on: push

env:
  docker_username: ${{ github.repository_owner }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  VERSION_TAG: 0.0.1

jobs: 
  Test:
    runs-on: self-hosted
    container: golang:1.21.0-bookworm
    steps:
      - name: clone-down
        uses: actions/checkout@v3
      - name: Test
        run: chmod +x ci/unit-test.sh && ci/unit-test.sh
  Docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: clone-down
        uses: actions/checkout@v3
      - name: docker compose build
        run: docker compose build
      - name: docker push
        run: chmod +x ci/docker-push.sh && ci/docker-push.sh
